# Generated by Django 5.1.5 on 2025-04-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="inventory_type",
            field=models.CharField(
                choices=[
                    ("MOSQUE_DONATION", "Donation for Mosque"),
                    ("NEEDY_DONATION", "Donation for Needy"),
                    ("ORG_FUNDS", "Organization Funds"),
                    ("LOAN_FUNDS", "Loan Funds"),
                ],
                max_length=20,
            ),
        ),
    ]
