# Generated by Django 5.1.5 on 2025-04-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_inventory_inventory_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="prev_amount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="transaction",
            name="loan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="mosque_donation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="needy_donation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="activity",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAW", "Withdraw"),
                    ("FEE", "Fee"),
                ],
                max_length=20,
            ),
        ),
    ]
