# Generated by Django 5.1.5 on 2025-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_transaction_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_img",
            field=models.ImageField(blank=True, null=True, upload_to="accounts/"),
        ),
    ]
