# Generated by Django 5.1.5 on 2025-05-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_account_account_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("account_info", "Account Info"),
                            ("loan", "Loan"),
                            ("loan_paid", "Loan Paid"),
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                        ],
                        max_length=255,
                    ),
                ),
                ("field_id", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="accounts/{}")),
            ],
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_img",
        ),
    ]
